### ISSUE TITLE
Error in normalizeCounts for VisiumHD SPATA2 object 

### ISSUE THREAD

**Issue by vfincke** [theMILOlab/SPATA2#157]
Dear team, 

I get an error when following your tutorial in the normalizeCounts command: 

spata_obj <- normalizeCounts(spata_obj, method = "LogNormalize")
Normalizing layer: counts
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
13:02:00 Active matrix in assay 'gene': 'LogNormalize'
Error in `map2()`:
ℹ In index: 3.
ℹ With name: sct_clip_range.
Caused by error:
! object 'umi' not found
Run `rlang::last_trace()` to see where the error occurred.
> spata_obj
SPATA2 object of size: 175528 x 18063 (spots x molecules)
Sample name: eMRTskin 
Platform: VisiumHD 
Molecular assays (1):
1. Assay
 Molecular modality: gene
 Distinct molecules: 18063
 Matrices (1):
 -counts (active)
Images (1):
- lowres (600x595 px, active)
Meta variables (5): sample, tissue_section, n_counts_gene, n_distinct_gene, avg_cpm_gene

Can you help me fixing this error? 
Thank you very much and kind regards, 

Victoria

**Comment by kueckelj** [comment]
Hi, can you try with `sct_clip_range = NULL` ? This is not going to affect your results since you are using LogNormalize. 

`object <- normalizeCounts(object, method = "LogNormalize", sct_clip_range = NULL)`

Does that work? 

(The error comes from a deeper problem with how the information about the function you used is stored in the logfile data of the SPATA2 object. Nothing you need to bother yourself with.)

**Comment by vfincke** [comment]
That worked - thank you very much for the quick help!!
