### ISSUE TITLE
SPATA2::createSegmentation(spata_object) does not save the segmentation

### ISSUE THREAD

**Issue by lsudupe** [theMILOlab/SPATA2#34]
I am using the SPATA2::createSegmentation() function. After I create the segmentation and save it I close the shiny or browser with "close the application" bottom and process to use the SPATA2::plotSegmentation() function.

It raised me this advertise "Sample dpi3 has not been segmented yet."

am I forgetting some step?

![Screen Shot 2022-05-15 at 11 56 27 AM](https://user-images.githubusercontent.com/68045564/168465000-884490a0-205e-44fc-a223-623cd84e8e6f.png)
![Screen Shot 2022-05-15 at 11 57 38 AM](https://user-images.githubusercontent.com/68045564/168465015-7c3b2a69-1496-4a4c-b310-994d445e764d.png)

**Comment by kueckelj** [comment]
Hi Isudupe, 
I can not reproduce the error. Can you copy and paste me the complete codechunk you used to segment the sample and to plot it? Does your code include the following: 

# close with `Close application` (as you described)` 
`spata_object <- createSegmentation(object = spata_object)`

# plot
`plotSegmentation(object = spata_object)`

What happens if you plot the segmentation with:
`plotSurface(object = spata_object, color_by = "segmentation")`

**Comment by lsudupe** [comment]
Apologize, here is the code:

dpi3 <- readRDS(path)

SPATA2::dpi3_spata <- transformSeuratToSpata(
  dpi3,
  sample_name = "dpi3",
  method = "spatial",
  coords_from = "pca",
  assay_name = "SCT",
  assay_slot = NULL,
  image_name = "dpi3",
  gene_set_path = NULL,
  verbose = TRUE
)

SPATA2::createSegmentation(dpi3_spata)
SPATA2::plotSegmentation(object = dpi3_spata)

If I do plotSurface(object = spata_object, color_by = "segmentation") I get this, the problem is that the segmentation I create it is not save in the object when I close the browser or the application.

![Screen Shot 2022-05-15 at 3 10 08 PM](https://user-images.githubusercontent.com/68045564/168472069-d7f0e42f-434e-41de-9416-6ee3ed287896.png)

**Comment by kueckelj** [comment]
To save the segmentation results you need to save the output of `createSegmentation(object = dpi3_spata)`. From the code you posted it doesn't seem that you are doing that. 

Instead of `createSegmentation(object = dpi3_spata)` try `dpi3_spata <- createSegmentation(object = dpi3_spata)`. Does that work?

**Comment by lsudupe** [comment]
It works! Thank you so much for your help, apologize for that simple mistake of my side

**Comment by kueckelj** [comment]
No problem at all. Happy to help. :)
