### ISSUE TITLE
Error in run 'runGSEA'

### ISSUE THREAD

**Issue by Knight1995** [theMILOlab/SPATA2#50]
it is a great job.But I run the code using my data and it error as follow:
Error in confuns::give_feedback(msg = msg, fdb.fn = fdb.fn, with.time = with.time,  : 

![1671960185811](https://user-images.githubusercontent.com/88174091/209462848-7a9125fb-5807-4252-98f0-d13facb9f56e.jpg)
What should i do to deal with this problem? Thanks.

**Comment by kueckelj** [comment]
What is the output of `printDeaOverview(spata_obj)`?

**Comment by Knight1995** [comment]
Thanks for the reminder.  I didn't do a difference analysis before running GSEA.  This problem has now been solved.  Besides, what species does ‘runGSEA’ use?  Does that include mouse?  thanks.

**Comment by kueckelj** [comment]
I am sorry, I don't know exactly what you mean with "which species does runGSEA use". GSEA in general takes differentially expressed genes (DEA results) of a group and tests which gene sets are upregulated in this group based on the DEA results. A variety of gene sets are stored in the spata2 object. You can extract and skim them via `getGeneSetDf()` or `getGeneSetList()`. The gene sets SPATA2 provides are downloaded from a gene set data.base. See `?gsdf` for more information. You can add specific gene sets via `addGeneSets()` if you have gene sets that are not included in the default collection of SPATA2. Does that answer your question? If not, please elaborate so that I can help you.

**Comment by Knight1995** [comment]
I am sorry,I would like to know whether SPATA2 can be applied to the spatial transcriptome of other species besides human, such as mouse spatial transcriptome transcriptome? thanks

**Comment by kueckelj** [comment]
Of course it can!

**Comment by Knight1995** [comment]
It's great! thanks for your help.

**Comment by kueckelj** [comment]
Your welcome. Happy to help.
