### ISSUE TITLE
How to analysis multi slice visium object？

### ISSUE THREAD

**Issue by hzongyao** [theMILOlab/SPATA2#7]
My seurat obj contain multi slice outcome ，how to apply SPATA pipline analyse next step? Thank you !

**Comment by kueckelj** [comment]
Hello hzongyao, 
what exactly do you mean with 'multi slice visium object'? Did you merge two or more seurat objects with the `merge()` function?

**Comment by hzongyao** [comment]
Hi thank you !
 I just saw realted Merge Spata Objects function in code,I will try to use it !


Thanks!

**Comment by kueckelj** [comment]
Hi, if you are looking to analyze several Visium samples within one and the same spata object: This is currently not possible. We have deprecated the multiple sample options. This is because the objects size becomes too big and SPATA does not offer any functionalities with multiple slices. Plotting two surface plots next to each other as shown with the `brain.merge`-object in the Seurat [tutorial](https://satijalab.org/seurat/articles/spatial_vignette.html) can be easily done with the `+`-operator from the package `patchwork.` Apart from that, having mulitple samples in one and the same SPATA object does not have any advantages. We are planning to integrate more analysis features in the future. Till then I recommend sticking to one sample per spata object. 

If you want to analyze both samples with SPATA you'll have to transform the original seurat objects (before you merged them) to single spata objects via `transformSpataToSeurat()`. 


Best regards 

Jan
